version: '3.9'
services:
  db:
    image: postgres:latest
    ports:
      - "1926:5432"
    environment:
      POSTGRES_USER: donantonio
      POSTGRES_PASSWORD: lasonrisa
      POSTGRES_DB: dietiestates